import { NextIntlClientProvider } from "next-intl";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

import ShopContextProvider from "@/context/ShopContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ShopContextProvider>
          <NextIntlClientProvider>
            <div className="h-screen flex flex-col justify-between">
              <Navbar />
              <div className="py-4 px-4 sm:px-[5vw] md:px-[7vw] lg:px-[9vw]">
                {children}
              </div>
              <Footer />
            </div>
          </NextIntlClientProvider>
        </ShopContextProvider>
      </body>
    </html>
  );
}
